### ISSUE TITLE
Comments are taken into account when slashes are forbidden in the test

### ISSUE THREAD

**Issue by El-Loco-Pinguino** [nan-academy/js-training#6]
> const volvAbs = (x) => { // Stupid negatives
> return (x < 0) ? -x : x
> }

The slashes used for commenting make the test `assert.strictEqual(_function_.toString().includes('/'), false)` fail.

**Comment by kigiri** [comment]
Yeah tests are very naives, because i expect beginners to read them.
I think it's actualy fairly understandable what is the issue on this test.

They are here just as an indication to what kind of things not to do, you may comment a test that you think is bad.

I plan to make a better tester that is online, you would have the online tester with fiables and complete tests and your local test that are more here for guiding in the proper direction, giving exemple on how to write your own tests.

For now only those are available.
